2025-09-24 06:41:43 - INFO - ###############################
2025-09-24 06:41:43 - INFO - TEST INFO LOGGING FINALLY
2025-09-24 06:41:43 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-24 06:41:43 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-24 06:41:43 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-24 06:41:43 - INFO - LOGGER STARTED
2025-09-24 06:41:43 - INFO - ###############################
2025-09-24 06:41:43 - INFO - Stated connect to db
2025-09-24 06:41:43 - INFO - Users db created/exist
2025-09-24 06:41:44 - INFO - WS Parser started!
2025-09-24 06:41:44 - INFO - Getting data from server
2025-09-24 06:41:46 - INFO - Start schedule normalization
2025-09-24 06:41:46 - INFO - Schedule is the same. Cancel.
2025-09-24 06:41:46 - INFO - Data received from server
2025-09-24 06:46:46 - INFO - Getting data from server
2025-09-24 06:46:47 - INFO - Start schedule normalization
2025-09-24 06:46:47 - INFO - Schedule is the same. Cancel.
2025-09-24 06:46:47 - INFO - Data received from server
2025-09-24 06:51:47 - INFO - Getting data from server
2025-09-24 06:51:49 - INFO - Start schedule normalization
2025-09-24 06:51:49 - INFO - Schedule is the same. Cancel.
2025-09-24 06:51:49 - INFO - Data received from server
2025-09-24 06:56:49 - INFO - Getting data from server
2025-09-24 06:56:50 - INFO - Start schedule normalization
2025-09-24 06:56:50 - INFO - Schedule normalized
2025-09-24 06:56:50 - INFO - Data received from server
2025-09-24 07:01:50 - INFO - Getting data from server
2025-09-24 07:01:52 - INFO - Start schedule normalization
2025-09-24 07:01:52 - INFO - Schedule is the same. Cancel.
2025-09-24 07:01:52 - INFO - Data received from server
2025-09-24 07:06:52 - INFO - Getting data from server
2025-09-24 07:06:53 - INFO - Start schedule normalization
2025-09-24 07:06:54 - INFO - Schedule is the same. Cancel.
2025-09-24 07:06:54 - INFO - Data received from server
2025-09-24 07:11:54 - INFO - Getting data from server
2025-09-24 07:11:55 - INFO - Start schedule normalization
2025-09-24 07:11:55 - INFO - Schedule is the same. Cancel.
2025-09-24 07:11:55 - INFO - Data received from server
2025-09-24 07:16:55 - INFO - Getting data from server
2025-09-24 07:16:57 - INFO - Start schedule normalization
2025-09-24 07:16:57 - INFO - Schedule is the same. Cancel.
2025-09-24 07:16:57 - INFO - Data received from server
2025-09-24 07:21:57 - INFO - Getting data from server
2025-09-24 07:21:58 - INFO - Start schedule normalization
2025-09-24 07:21:58 - INFO - Schedule is the same. Cancel.
2025-09-24 07:21:58 - INFO - Data received from server
2025-09-24 07:26:58 - INFO - Getting data from server
2025-09-24 07:27:00 - INFO - Start schedule normalization
2025-09-24 07:27:00 - INFO - Schedule is the same. Cancel.
2025-09-24 07:27:00 - INFO - Data received from server
2025-09-24 07:32:00 - INFO - Getting data from server
2025-09-24 07:32:01 - INFO - Start schedule normalization
2025-09-24 07:32:01 - INFO - Schedule is the same. Cancel.
2025-09-24 07:32:01 - INFO - Data received from server
2025-09-24 07:37:01 - INFO - Getting data from server
2025-09-24 07:37:03 - INFO - Start schedule normalization
2025-09-24 07:37:03 - INFO - Schedule is the same. Cancel.
2025-09-24 07:37:03 - INFO - Data received from server
2025-09-24 07:42:03 - INFO - Getting data from server
2025-09-24 07:42:04 - INFO - Start schedule normalization
2025-09-24 07:42:04 - INFO - Schedule is the same. Cancel.
2025-09-24 07:42:04 - INFO - Data received from server
2025-09-24 07:43:33 - INFO - 6983370282 used GET SCHEDULE FUNC and choice Среда
2025-09-24 07:47:04 - INFO - Getting data from server
2025-09-24 07:47:06 - INFO - Start schedule normalization
2025-09-24 07:47:06 - INFO - Schedule is the same. Cancel.
2025-09-24 07:47:06 - INFO - Data received from server
2025-09-24 07:50:42 - INFO - 6983370282 used GET SCHEDULE FUNC and choice Четверг
2025-09-24 07:50:50 - INFO - 6983370282 used GET SCHEDULE FUNC and choice Четверг
2025-09-24 07:51:04 - ERROR - Infinity polling exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-09-24 07:51:04 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1430, in getresponse
    response.begin()
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1430, in getresponse
    response.begin()
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 9759, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\telegram_bot\main.py", line 273, in get_schedule_for_user
    bot.send_message(message.from_user.id,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1800, in send_message
    apihelper.send_message(
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    result = _get_req_session().request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

2025-09-24 07:52:06 - INFO - Getting data from server
2025-09-24 07:52:07 - INFO - Start schedule normalization
2025-09-24 07:52:07 - INFO - Schedule is the same. Cancel.
2025-09-24 07:52:07 - INFO - Data received from server
2025-09-24 07:57:07 - INFO - Getting data from server
2025-09-24 07:57:08 - INFO - Start schedule normalization
2025-09-24 07:57:09 - INFO - Schedule is the same. Cancel.
2025-09-24 07:57:09 - INFO - Data received from server
2025-09-24 08:02:09 - INFO - Getting data from server
2025-09-24 08:02:10 - INFO - Start schedule normalization
2025-09-24 08:02:10 - INFO - Schedule is the same. Cancel.
2025-09-24 08:02:10 - INFO - Data received from server
2025-09-24 08:07:10 - INFO - Getting data from server
2025-09-24 08:07:11 - INFO - Start schedule normalization
2025-09-24 08:07:11 - INFO - Schedule is the same. Cancel.
2025-09-24 08:07:11 - INFO - Data received from server
2025-09-24 08:12:11 - INFO - Getting data from server
2025-09-24 08:12:13 - INFO - Start schedule normalization
2025-09-24 08:12:13 - INFO - Schedule is the same. Cancel.
2025-09-24 08:12:13 - INFO - Data received from server
2025-09-24 08:17:13 - INFO - Getting data from server
2025-09-24 08:17:14 - INFO - Start schedule normalization
2025-09-24 08:17:14 - INFO - Schedule is the same. Cancel.
2025-09-24 08:17:14 - INFO - Data received from server
2025-09-24 08:22:14 - INFO - Getting data from server
2025-09-24 08:22:16 - INFO - Start schedule normalization
2025-09-24 08:22:16 - INFO - Schedule is the same. Cancel.
2025-09-24 08:22:16 - INFO - Data received from server
2025-09-24 08:27:16 - INFO - Getting data from server
2025-09-24 08:27:17 - INFO - Start schedule normalization
2025-09-24 08:27:17 - INFO - Schedule is the same. Cancel.
2025-09-24 08:27:17 - INFO - Data received from server
2025-09-24 08:32:17 - INFO - Getting data from server
2025-09-24 08:32:18 - INFO - Start schedule normalization
2025-09-24 08:32:18 - INFO - Schedule is the same. Cancel.
2025-09-24 08:32:18 - INFO - Data received from server
2025-09-24 08:37:18 - INFO - Getting data from server
2025-09-24 08:37:20 - INFO - Start schedule normalization
2025-09-24 08:37:20 - INFO - Schedule is the same. Cancel.
2025-09-24 08:37:20 - INFO - Data received from server
2025-09-24 08:42:20 - INFO - Getting data from server
2025-09-24 08:42:41 - INFO - Data received from server
2025-09-24 08:47:41 - INFO - Getting data from server
2025-09-24 08:47:42 - INFO - Start schedule normalization
2025-09-24 08:47:43 - INFO - Schedule is the same. Cancel.
2025-09-24 08:47:43 - INFO - Data received from server
2025-09-24 08:52:43 - INFO - Getting data from server
2025-09-24 08:52:44 - INFO - Start schedule normalization
2025-09-24 08:52:44 - INFO - Schedule is the same. Cancel.
2025-09-24 08:52:44 - INFO - Data received from server
2025-09-24 08:57:44 - INFO - Getting data from server
2025-09-24 08:57:45 - INFO - Start schedule normalization
2025-09-24 08:57:46 - INFO - Schedule is the same. Cancel.
2025-09-24 08:57:46 - INFO - Data received from server
2025-09-24 09:02:46 - INFO - Getting data from server
2025-09-24 09:02:47 - INFO - Start schedule normalization
2025-09-24 09:02:47 - INFO - Schedule is the same. Cancel.
2025-09-24 09:02:47 - INFO - Data received from server
2025-09-24 09:07:47 - INFO - Getting data from server
2025-09-24 09:07:48 - INFO - Start schedule normalization
2025-09-24 09:07:49 - INFO - Schedule is the same. Cancel.
2025-09-24 09:07:49 - INFO - Data received from server
2025-09-24 09:12:49 - INFO - Getting data from server
2025-09-24 09:12:50 - INFO - Start schedule normalization
2025-09-24 09:12:50 - INFO - Schedule is the same. Cancel.
2025-09-24 09:12:50 - INFO - Data received from server
2025-09-24 09:17:50 - INFO - Getting data from server
2025-09-24 09:17:51 - INFO - Start schedule normalization
2025-09-24 09:17:51 - INFO - Schedule is the same. Cancel.
2025-09-24 09:17:51 - INFO - Data received from server
2025-09-24 09:22:51 - INFO - Getting data from server
2025-09-24 09:22:53 - INFO - Start schedule normalization
2025-09-24 09:22:53 - INFO - Schedule is the same. Cancel.
2025-09-24 09:22:53 - INFO - Data received from server
2025-09-24 09:27:53 - INFO - Getting data from server
2025-09-24 09:27:54 - INFO - Start schedule normalization
2025-09-24 09:27:54 - INFO - Schedule is the same. Cancel.
2025-09-24 09:27:54 - INFO - Data received from server
2025-09-24 09:32:54 - INFO - Getting data from server
2025-09-24 09:32:56 - INFO - Start schedule normalization
2025-09-24 09:32:56 - INFO - Schedule is the same. Cancel.
2025-09-24 09:32:56 - INFO - Data received from server
2025-09-24 09:37:56 - INFO - Getting data from server
2025-09-24 09:37:57 - INFO - Start schedule normalization
2025-09-24 09:37:57 - INFO - Schedule is the same. Cancel.
2025-09-24 09:37:57 - INFO - Data received from server
2025-09-24 09:42:57 - INFO - Getting data from server
2025-09-24 09:42:59 - INFO - Start schedule normalization
2025-09-24 09:42:59 - INFO - Schedule is the same. Cancel.
2025-09-24 09:42:59 - INFO - Data received from server
2025-09-24 09:47:59 - INFO - Getting data from server
2025-09-24 09:48:00 - INFO - Start schedule normalization
2025-09-24 09:48:00 - INFO - Schedule is the same. Cancel.
2025-09-24 09:48:00 - INFO - Data received from server
2025-09-24 09:53:00 - INFO - Getting data from server
2025-09-24 09:53:02 - INFO - Start schedule normalization
2025-09-24 09:53:02 - INFO - Schedule is the same. Cancel.
2025-09-24 09:53:02 - INFO - Data received from server
2025-09-24 09:58:02 - INFO - Getting data from server
2025-09-24 09:58:04 - INFO - Start schedule normalization
2025-09-24 09:58:04 - INFO - Schedule is the same. Cancel.
2025-09-24 09:58:04 - INFO - Data received from server
2025-09-24 10:03:04 - INFO - Getting data from server
2025-09-24 10:03:05 - INFO - Start schedule normalization
2025-09-24 10:03:05 - INFO - Schedule is the same. Cancel.
2025-09-24 10:03:05 - INFO - Data received from server
2025-09-24 10:08:05 - INFO - Getting data from server
2025-09-24 10:08:07 - INFO - Start schedule normalization
2025-09-24 10:08:07 - INFO - Schedule is the same. Cancel.
2025-09-24 10:08:07 - INFO - Data received from server
2025-09-24 10:13:07 - INFO - Getting data from server
2025-09-24 10:13:08 - INFO - Start schedule normalization
2025-09-24 10:13:09 - INFO - Schedule is the same. Cancel.
2025-09-24 10:13:09 - INFO - Data received from server
2025-09-24 10:18:09 - INFO - Getting data from server
2025-09-24 10:18:30 - INFO - Data received from server
2025-09-24 10:23:30 - INFO - Getting data from server
2025-09-24 10:23:31 - INFO - Start schedule normalization
2025-09-24 10:23:31 - INFO - Schedule is the same. Cancel.
2025-09-24 10:23:31 - INFO - Data received from server
2025-09-24 10:28:31 - INFO - Getting data from server
2025-09-24 10:28:33 - INFO - Start schedule normalization
2025-09-24 10:28:33 - INFO - Schedule is the same. Cancel.
2025-09-24 10:28:33 - INFO - Data received from server
2025-09-24 10:33:33 - INFO - Getting data from server
2025-09-24 10:33:34 - INFO - Start schedule normalization
2025-09-24 10:33:34 - INFO - Schedule is the same. Cancel.
2025-09-24 10:33:34 - INFO - Data received from server
2025-09-24 10:38:34 - INFO - Getting data from server
2025-09-24 10:38:35 - INFO - Start schedule normalization
2025-09-24 10:38:36 - INFO - Schedule is the same. Cancel.
2025-09-24 10:38:36 - INFO - Data received from server
2025-09-24 10:43:36 - INFO - Getting data from server
2025-09-24 10:43:37 - INFO - Start schedule normalization
2025-09-24 10:43:37 - INFO - Schedule is the same. Cancel.
2025-09-24 10:43:37 - INFO - Data received from server
2025-09-24 10:48:37 - INFO - Getting data from server
2025-09-24 10:48:38 - INFO - Start schedule normalization
2025-09-24 10:48:39 - INFO - Schedule is the same. Cancel.
2025-09-24 10:48:39 - INFO - Data received from server
2025-09-24 10:53:39 - INFO - Getting data from server
2025-09-24 10:53:40 - INFO - Start schedule normalization
2025-09-24 10:53:40 - INFO - Schedule is the same. Cancel.
2025-09-24 10:53:40 - INFO - Data received from server
2025-09-24 10:58:40 - INFO - Getting data from server
2025-09-24 10:58:41 - INFO - Start schedule normalization
2025-09-24 10:58:42 - INFO - Schedule is the same. Cancel.
2025-09-24 10:58:42 - INFO - Data received from server
2025-09-24 11:03:42 - INFO - Getting data from server
2025-09-24 11:03:43 - INFO - Start schedule normalization
2025-09-24 11:03:43 - INFO - Schedule is the same. Cancel.
2025-09-24 11:03:43 - INFO - Data received from server
2025-09-24 11:08:43 - INFO - Getting data from server
2025-09-24 11:08:44 - INFO - Start schedule normalization
2025-09-24 11:08:44 - INFO - Schedule is the same. Cancel.
2025-09-24 11:08:44 - INFO - Data received from server
2025-09-24 11:13:44 - INFO - Getting data from server
2025-09-24 11:13:46 - INFO - Start schedule normalization
2025-09-24 11:13:46 - INFO - Schedule is the same. Cancel.
2025-09-24 11:13:46 - INFO - Data received from server
2025-09-24 11:18:46 - INFO - Getting data from server
2025-09-24 11:19:07 - INFO - Data received from server
2025-09-24 11:24:07 - INFO - Getting data from server
2025-09-24 11:24:08 - INFO - Start schedule normalization
2025-09-24 11:24:08 - INFO - Schedule is the same. Cancel.
2025-09-24 11:24:08 - INFO - Data received from server
2025-09-24 11:29:08 - INFO - Getting data from server
2025-09-24 11:29:10 - INFO - Start schedule normalization
2025-09-24 11:29:10 - INFO - Schedule is the same. Cancel.
2025-09-24 11:29:10 - INFO - Data received from server
2025-09-24 11:34:10 - INFO - Getting data from server
2025-09-24 11:34:11 - INFO - Start schedule normalization
2025-09-24 11:34:11 - INFO - Schedule is the same. Cancel.
2025-09-24 11:34:11 - INFO - Data received from server
2025-09-24 11:39:11 - INFO - Getting data from server
2025-09-24 11:39:13 - INFO - Start schedule normalization
2025-09-24 11:39:13 - INFO - Schedule is the same. Cancel.
2025-09-24 11:39:13 - INFO - Data received from server
2025-09-24 11:44:13 - INFO - Getting data from server
2025-09-24 11:44:14 - INFO - Start schedule normalization
2025-09-24 11:44:14 - INFO - Schedule is the same. Cancel.
2025-09-24 11:44:14 - INFO - Data received from server
2025-09-24 11:49:14 - INFO - Getting data from server
2025-09-24 11:49:16 - INFO - Start schedule normalization
2025-09-24 11:49:16 - INFO - Schedule is the same. Cancel.
2025-09-24 11:49:16 - INFO - Data received from server
2025-09-24 11:54:16 - INFO - Getting data from server
2025-09-24 11:54:17 - INFO - Start schedule normalization
2025-09-24 11:54:17 - INFO - Schedule is the same. Cancel.
2025-09-24 11:54:17 - INFO - Data received from server
2025-09-24 11:59:17 - INFO - Getting data from server
2025-09-24 11:59:18 - INFO - Start schedule normalization
2025-09-24 11:59:19 - INFO - Schedule is the same. Cancel.
2025-09-24 11:59:19 - INFO - Data received from server
2025-09-24 12:04:19 - INFO - Getting data from server
2025-09-24 12:04:20 - INFO - Start schedule normalization
2025-09-24 12:04:20 - INFO - Schedule is the same. Cancel.
2025-09-24 12:04:20 - INFO - Data received from server
2025-09-24 12:09:20 - INFO - Getting data from server
2025-09-24 12:09:21 - INFO - Start schedule normalization
2025-09-24 12:09:22 - INFO - Schedule is the same. Cancel.
2025-09-24 12:09:22 - INFO - Data received from server
2025-09-24 12:14:22 - INFO - Getting data from server
2025-09-24 12:14:23 - INFO - Start schedule normalization
2025-09-24 12:14:23 - INFO - Schedule is the same. Cancel.
2025-09-24 12:14:23 - INFO - Data received from server
2025-09-24 12:19:23 - INFO - Getting data from server
2025-09-24 12:19:25 - INFO - Start schedule normalization
2025-09-24 12:19:25 - INFO - Schedule is the same. Cancel.
2025-09-24 12:19:25 - INFO - Data received from server
2025-09-24 12:24:25 - INFO - Getting data from server
2025-09-24 12:24:26 - INFO - Start schedule normalization
2025-09-24 12:24:26 - INFO - Schedule is the same. Cancel.
2025-09-24 12:24:26 - INFO - Data received from server
2025-09-24 12:29:26 - INFO - Getting data from server
2025-09-24 12:29:27 - INFO - Start schedule normalization
2025-09-24 12:29:27 - INFO - Schedule is the same. Cancel.
2025-09-24 12:29:27 - INFO - Data received from server
2025-09-24 12:34:27 - INFO - Getting data from server
2025-09-24 12:34:29 - INFO - Start schedule normalization
2025-09-24 12:34:29 - INFO - Schedule is the same. Cancel.
2025-09-24 12:34:29 - INFO - Data received from server
2025-09-24 12:39:29 - INFO - Getting data from server
2025-09-24 12:39:30 - INFO - Start schedule normalization
2025-09-24 12:39:30 - INFO - Schedule is the same. Cancel.
2025-09-24 12:39:30 - INFO - Data received from server
2025-09-24 12:44:30 - INFO - Getting data from server
2025-09-24 12:44:32 - INFO - Start schedule normalization
2025-09-24 12:44:32 - INFO - Schedule is the same. Cancel.
2025-09-24 12:44:32 - INFO - Data received from server
2025-09-24 12:49:32 - INFO - Getting data from server
2025-09-24 12:49:34 - INFO - Start schedule normalization
2025-09-24 12:49:34 - INFO - Schedule is the same. Cancel.
2025-09-24 12:49:34 - INFO - Data received from server
2025-09-24 12:54:34 - INFO - Getting data from server
2025-09-24 12:54:35 - INFO - Start schedule normalization
2025-09-24 12:54:35 - INFO - Schedule is the same. Cancel.
2025-09-24 12:54:35 - INFO - Data received from server
2025-09-24 12:59:35 - INFO - Getting data from server
2025-09-24 12:59:36 - INFO - Start schedule normalization
2025-09-24 12:59:36 - INFO - Schedule is the same. Cancel.
2025-09-24 12:59:36 - INFO - Data received from server
2025-09-24 13:04:36 - INFO - Getting data from server
2025-09-24 13:04:38 - INFO - Start schedule normalization
2025-09-24 13:04:38 - INFO - Schedule is the same. Cancel.
2025-09-24 13:04:38 - INFO - Data received from server
2025-09-24 13:09:38 - INFO - Getting data from server
2025-09-24 13:09:39 - INFO - Start schedule normalization
2025-09-24 13:09:39 - INFO - Schedule is the same. Cancel.
2025-09-24 13:09:39 - INFO - Data received from server
2025-09-24 13:14:39 - INFO - Getting data from server
2025-09-24 13:14:41 - INFO - Start schedule normalization
2025-09-24 13:14:41 - INFO - Schedule is the same. Cancel.
2025-09-24 13:14:41 - INFO - Data received from server
2025-09-24 13:19:41 - INFO - Getting data from server
2025-09-24 13:19:43 - INFO - Start schedule normalization
2025-09-24 13:19:43 - INFO - Schedule is the same. Cancel.
2025-09-24 13:19:43 - INFO - Data received from server
2025-09-24 13:24:43 - INFO - Getting data from server
2025-09-24 13:24:44 - INFO - Start schedule normalization
2025-09-24 13:24:44 - INFO - Schedule is the same. Cancel.
2025-09-24 13:24:44 - INFO - Data received from server
2025-09-24 13:29:44 - INFO - Getting data from server
2025-09-24 13:29:46 - INFO - Start schedule normalization
2025-09-24 13:29:46 - INFO - Schedule is the same. Cancel.
2025-09-24 13:29:46 - INFO - Data received from server
2025-09-24 13:34:46 - INFO - Getting data from server
2025-09-24 13:34:47 - INFO - Start schedule normalization
2025-09-24 13:34:47 - INFO - Schedule is the same. Cancel.
2025-09-24 13:34:47 - INFO - Data received from server
2025-09-24 13:39:47 - INFO - Getting data from server
2025-09-24 13:39:48 - INFO - Start schedule normalization
2025-09-24 13:39:48 - INFO - Schedule is the same. Cancel.
2025-09-24 13:39:48 - INFO - Data received from server
2025-09-24 13:44:48 - INFO - Getting data from server
2025-09-24 13:44:50 - INFO - Start schedule normalization
2025-09-24 13:44:50 - INFO - Schedule is the same. Cancel.
2025-09-24 13:44:50 - INFO - Data received from server
2025-09-24 13:49:50 - INFO - Getting data from server
2025-09-24 13:49:51 - INFO - Start schedule normalization
2025-09-24 13:49:51 - INFO - Schedule is the same. Cancel.
2025-09-24 13:49:51 - INFO - Data received from server
2025-09-24 13:54:51 - INFO - Getting data from server
2025-09-24 13:54:53 - INFO - Start schedule normalization
2025-09-24 13:54:53 - INFO - Schedule is the same. Cancel.
2025-09-24 13:54:53 - INFO - Data received from server
2025-09-24 13:59:53 - INFO - Getting data from server
2025-09-24 13:59:54 - INFO - Start schedule normalization
2025-09-24 13:59:54 - INFO - Schedule is the same. Cancel.
2025-09-24 13:59:54 - INFO - Data received from server
2025-09-24 14:04:54 - INFO - Getting data from server
2025-09-24 14:04:55 - INFO - Start schedule normalization
2025-09-24 14:04:55 - INFO - Schedule is the same. Cancel.
2025-09-24 14:04:55 - INFO - Data received from server
2025-09-24 14:09:55 - INFO - Getting data from server
2025-09-24 14:09:57 - INFO - Start schedule normalization
2025-09-24 14:09:57 - INFO - Schedule is the same. Cancel.
2025-09-24 14:09:57 - INFO - Data received from server
2025-09-24 14:14:57 - INFO - Getting data from server
2025-09-24 14:14:59 - INFO - Start schedule normalization
2025-09-24 14:14:59 - INFO - Schedule is the same. Cancel.
2025-09-24 14:14:59 - INFO - Data received from server
2025-09-24 14:19:59 - INFO - Getting data from server
2025-09-24 14:20:00 - INFO - Start schedule normalization
2025-09-24 14:20:00 - INFO - Schedule is the same. Cancel.
2025-09-24 14:20:00 - INFO - Data received from server
2025-09-24 14:25:00 - INFO - Getting data from server
2025-09-24 14:25:01 - INFO - Start schedule normalization
2025-09-24 14:25:01 - INFO - Schedule is the same. Cancel.
2025-09-24 14:25:01 - INFO - Data received from server
2025-09-24 14:30:01 - INFO - Getting data from server
2025-09-24 14:30:03 - INFO - Start schedule normalization
2025-09-24 14:30:03 - INFO - Schedule is the same. Cancel.
2025-09-24 14:30:03 - INFO - Data received from server
2025-09-24 14:35:03 - INFO - Getting data from server
2025-09-24 14:35:04 - INFO - Start schedule normalization
2025-09-24 14:35:04 - INFO - Schedule is the same. Cancel.
2025-09-24 14:35:04 - INFO - Data received from server
2025-09-24 14:40:04 - INFO - Getting data from server
2025-09-24 14:40:06 - INFO - Start schedule normalization
2025-09-24 14:40:06 - INFO - Schedule is the same. Cancel.
2025-09-24 14:40:06 - INFO - Data received from server
2025-09-24 14:45:06 - INFO - Getting data from server
2025-09-24 14:45:07 - INFO - Start schedule normalization
2025-09-24 14:45:07 - INFO - Schedule is the same. Cancel.
2025-09-24 14:45:07 - INFO - Data received from server
2025-09-24 14:50:07 - INFO - Getting data from server
2025-09-24 14:50:09 - INFO - Start schedule normalization
2025-09-24 14:50:09 - INFO - Schedule is the same. Cancel.
2025-09-24 14:50:09 - INFO - Data received from server
2025-09-24 14:55:09 - INFO - Getting data from server
2025-09-24 14:55:10 - INFO - Start schedule normalization
2025-09-24 14:55:10 - INFO - Schedule is the same. Cancel.
2025-09-24 14:55:10 - INFO - Data received from server
2025-09-24 14:57:37 - INFO - 6983370282 used GET SCHEDULE FUNC and choice Пятница
2025-09-24 14:57:46 - INFO - 6983370282 used GET SCHEDULE FUNC and choice Четверг
2025-09-24 15:00:10 - INFO - Getting data from server
2025-09-24 15:00:12 - INFO - Start schedule normalization
2025-09-24 15:00:12 - INFO - Schedule is the same. Cancel.
2025-09-24 15:00:12 - INFO - Data received from server
2025-09-24 15:05:12 - INFO - Getting data from server
2025-09-24 15:05:13 - INFO - Start schedule normalization
2025-09-24 15:05:13 - INFO - Schedule normalized
2025-09-24 15:05:13 - INFO - Data received from server
2025-09-24 15:10:13 - INFO - Getting data from server
2025-09-24 15:10:14 - INFO - Start schedule normalization
2025-09-24 15:10:14 - INFO - Schedule is the same. Cancel.
2025-09-24 15:10:14 - INFO - Data received from server
2025-09-24 15:15:14 - INFO - Getting data from server
2025-09-24 15:15:16 - INFO - Start schedule normalization
2025-09-24 15:15:16 - INFO - Schedule is the same. Cancel.
2025-09-24 15:15:16 - INFO - Data received from server
2025-09-24 15:20:16 - INFO - Getting data from server
2025-09-24 15:20:17 - INFO - Start schedule normalization
2025-09-24 15:20:17 - INFO - Schedule is the same. Cancel.
2025-09-24 15:20:17 - INFO - Data received from server
2025-09-24 15:25:17 - INFO - Getting data from server
2025-09-24 15:25:19 - INFO - Start schedule normalization
2025-09-24 15:25:19 - INFO - Schedule is the same. Cancel.
2025-09-24 15:25:19 - INFO - Data received from server
2025-09-24 15:30:19 - INFO - Getting data from server
2025-09-24 15:30:20 - INFO - Start schedule normalization
2025-09-24 15:30:20 - INFO - Schedule is the same. Cancel.
2025-09-24 15:30:20 - INFO - Data received from server
2025-09-24 15:35:20 - INFO - Getting data from server
2025-09-24 15:35:22 - INFO - Start schedule normalization
2025-09-24 15:35:22 - INFO - Schedule is the same. Cancel.
2025-09-24 15:35:22 - INFO - Data received from server
2025-09-24 15:40:22 - INFO - Getting data from server
2025-09-24 15:40:23 - INFO - Start schedule normalization
2025-09-24 15:40:23 - INFO - Schedule is the same. Cancel.
2025-09-24 15:40:23 - INFO - Data received from server
2025-09-24 15:45:23 - INFO - Getting data from server
2025-09-24 15:45:25 - INFO - Start schedule normalization
2025-09-24 15:45:25 - INFO - Schedule normalized
2025-09-24 15:45:25 - INFO - Data received from server
2025-09-24 15:50:25 - INFO - Getting data from server
2025-09-24 15:50:26 - INFO - Start schedule normalization
2025-09-24 15:50:26 - INFO - Schedule is the same. Cancel.
2025-09-24 15:50:26 - INFO - Data received from server
2025-09-24 15:55:26 - INFO - Getting data from server
2025-09-24 15:55:28 - INFO - Start schedule normalization
2025-09-24 15:55:28 - INFO - Schedule is the same. Cancel.
2025-09-24 15:55:28 - INFO - Data received from server
2025-09-24 16:00:28 - INFO - Getting data from server
2025-09-24 16:00:29 - INFO - Start schedule normalization
2025-09-24 16:00:29 - INFO - Schedule is the same. Cancel.
2025-09-24 16:00:29 - INFO - Data received from server
2025-09-24 16:04:10 - ERROR - Infinity polling exception: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D227423C0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-09-24 16:04:10 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 978, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000021D227423C0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D227423C0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    result = _get_req_session().request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D227423C0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))

2025-09-24 16:04:13 - ERROR - Infinity polling exception: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22856000>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-09-24 16:04:13 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 978, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000021D22856000>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22856000>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    result = _get_req_session().request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22856000>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))

2025-09-24 16:04:16 - ERROR - Infinity polling exception: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22E5CEC0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-09-24 16:04:16 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 978, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000021D22E5CEC0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22E5CEC0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    result = _get_req_session().request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22E5CEC0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))

2025-09-24 16:04:19 - ERROR - Infinity polling exception: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22855430>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-09-24 16:04:19 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazak\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 978, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000021D22855430>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22855430>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    result = _get_req_session().request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot8004422788:***********************************/getUpdates?offset=218512223&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021D22855430>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))

2025-09-24 16:05:29 - INFO - Getting data from server
2025-09-24 16:05:30 - INFO - Start schedule normalization
2025-09-24 16:05:30 - INFO - Schedule is the same. Cancel.
2025-09-24 16:05:30 - INFO - Data received from server
2025-09-24 16:10:30 - INFO - Getting data from server
2025-09-24 16:10:32 - INFO - Start schedule normalization
2025-09-24 16:10:32 - INFO - Schedule is the same. Cancel.
2025-09-24 16:10:32 - INFO - Data received from server
2025-09-24 16:15:32 - INFO - Getting data from server
2025-09-24 16:15:33 - INFO - Start schedule normalization
2025-09-24 16:15:33 - INFO - Schedule is the same. Cancel.
2025-09-24 16:15:33 - INFO - Data received from server
2025-09-24 16:20:33 - INFO - Getting data from server
2025-09-24 16:20:35 - INFO - Start schedule normalization
2025-09-24 16:20:35 - INFO - Schedule is the same. Cancel.
2025-09-24 16:20:35 - INFO - Data received from server
2025-09-24 16:25:35 - INFO - Getting data from server
2025-09-24 16:25:36 - INFO - Start schedule normalization
2025-09-24 16:25:36 - INFO - Schedule is the same. Cancel.
2025-09-24 16:25:36 - INFO - Data received from server
2025-09-24 16:30:36 - INFO - Getting data from server
2025-09-24 16:30:38 - INFO - Start schedule normalization
2025-09-24 16:30:38 - INFO - Schedule is the same. Cancel.
2025-09-24 16:30:38 - INFO - Data received from server
2025-09-24 16:35:38 - INFO - Getting data from server
2025-09-24 16:35:39 - INFO - Start schedule normalization
2025-09-24 16:35:39 - INFO - Schedule is the same. Cancel.
2025-09-24 16:35:39 - INFO - Data received from server
2025-09-24 16:40:39 - INFO - Getting data from server
2025-09-24 16:40:41 - INFO - Start schedule normalization
2025-09-24 16:40:41 - INFO - Schedule is the same. Cancel.
2025-09-24 16:40:41 - INFO - Data received from server
2025-09-24 16:45:41 - INFO - Getting data from server
2025-09-24 16:45:42 - INFO - Start schedule normalization
2025-09-24 16:45:42 - INFO - Schedule is the same. Cancel.
2025-09-24 16:45:42 - INFO - Data received from server
2025-09-24 16:50:42 - INFO - Getting data from server
2025-09-24 16:50:43 - INFO - Start schedule normalization
2025-09-24 16:50:44 - INFO - Schedule normalized
2025-09-24 16:50:44 - INFO - Data received from server
2025-09-24 16:55:44 - INFO - Getting data from server
2025-09-24 16:55:45 - INFO - Start schedule normalization
2025-09-24 16:55:45 - INFO - Schedule is the same. Cancel.
2025-09-24 16:55:45 - INFO - Data received from server
2025-09-24 17:00:45 - INFO - Getting data from server
2025-09-24 17:00:47 - INFO - Start schedule normalization
2025-09-24 17:00:47 - INFO - Schedule is the same. Cancel.
2025-09-24 17:00:47 - INFO - Data received from server
2025-09-24 17:05:47 - INFO - Getting data from server
2025-09-24 17:05:48 - INFO - Start schedule normalization
2025-09-24 17:05:49 - INFO - Schedule is the same. Cancel.
2025-09-24 17:05:49 - INFO - Data received from server
2025-09-24 17:10:49 - INFO - Getting data from server
2025-09-24 17:10:50 - INFO - Start schedule normalization
2025-09-24 17:10:50 - INFO - Schedule is the same. Cancel.
2025-09-24 17:10:50 - INFO - Data received from server
2025-09-24 17:15:50 - INFO - Getting data from server
2025-09-24 17:15:51 - INFO - Start schedule normalization
2025-09-24 17:15:51 - INFO - Schedule is the same. Cancel.
2025-09-24 17:15:51 - INFO - Data received from server
2025-09-24 17:20:51 - INFO - Getting data from server
2025-09-24 17:20:53 - INFO - Start schedule normalization
2025-09-24 17:20:53 - INFO - Schedule is the same. Cancel.
2025-09-24 17:20:53 - INFO - Data received from server
2025-09-24 17:24:32 - INFO - ###############################
2025-09-24 17:24:32 - INFO - TEST INFO LOGGING FINALLY
2025-09-24 17:24:32 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-24 17:25:03 - INFO - ###############################
2025-09-24 17:25:03 - INFO - TEST INFO LOGGING FINALLY
2025-09-24 17:25:03 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-24 17:25:03 - ERROR - Error Index: 0
Traceback (most recent call last):
  File "<input>", line 2, in <module>
NameError: name 'gfvhbjhn' is not defined
2025-09-24 17:25:03 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-24 17:25:03 - INFO - LOGGER STARTED
2025-09-24 17:25:03 - INFO - ###############################
2025-09-24 17:25:03 - INFO - Stated connect to db
2025-09-24 17:25:03 - INFO - Users db created/exist
2025-09-24 17:25:03 - ERROR - Error Index: 9
Traceback (most recent call last):
  File "<input>", line 2, in <module>
NameError: name 'gfvhbjhn' is not defined
2025-09-24 17:25:33 - INFO - ###############################
2025-09-24 17:25:33 - INFO - TEST INFO LOGGING FINALLY
2025-09-24 17:25:33 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-24 17:25:33 - ERROR - Error Index: 0
NoneType: None
2025-09-24 17:25:33 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-24 17:25:33 - INFO - LOGGER STARTED
2025-09-24 17:25:33 - INFO - ###############################
2025-09-24 17:25:33 - INFO - Stated connect to db
2025-09-24 17:25:33 - INFO - Users db created/exist
2025-09-24 17:25:33 - INFO - WS Parser started!
2025-09-24 17:25:33 - INFO - Getting data from server
2025-09-24 17:25:34 - INFO - Start schedule normalization
2025-09-24 17:25:34 - INFO - Schedule is the same. Cancel.
2025-09-24 17:25:34 - INFO - Data received from server
